[package]
name = "syncer"
version = "0.0.1"
edition = "2024"

[dependencies.bevy]
version = "0.17.*"
default-features = false
features = [
    "std",
    "bevy_asset",
    "file_watcher"
]

[dependencies]
shared = { path = "../shared" }
spacetimedb-sdk = "1.11.1"
bevy_spacetimedb = "0.7.2"